import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >


<Navbar />


          <main className="h-screen p-8 bg-gray-100 place-items-center place-content-center">{/* Main content area */}
            {children}
            </main>


        
        <footer className="p-4 bg-gray-800 text-white text-center">
          <p>&copy; 2024 My Next.js App</p>
          
        </footer>
      </body>
    </html>
  );
}
